homework done
Dimon4ik812/django_homework pull request #3
Opened 2024-09-20 16:41 UTC by Dimon4ik812

2024-09-20 17:19 UTC, painassasin requested changes

2024-09-20 17:19 UTC, painassasin commented on config/settings.py
> +    'catalog'
Тут запятую лучше бы оставил - она ставится в конце по PEP8

2024-09-20 17:19 UTC, painassasin commented on catalog/views.py
> +    product = Product.objects.get(id=product_id)
Корректнее получать продукт через `get_object_or_404`
```python
product = get_object_or_404(Product, pk=product_id)
```
Так, если продукт не найден, пользователь получит 404 ошибку и это корректная ошибка. А в твоем случае упадет исключение `Product.DoesNotExists` и пользователь получит 500

2024-09-20 17:19 UTC, painassasin commented on catalog/urls.py
> +    path('product_detail/<int:product_id>', product_detail, name='product_detail')
Давай закроем слешем, для единообразия

2024-09-20 17:19 UTC, painassasin commented on catalog/templates/product_information.html
> +<!DOCTYPE html>
Все шаблоны должны наследоваться от базового

У тебя должно остаться три эндпоинта (в urls.py, views.py):
- страница контактов
- страница с одним товаром
- страница со списком товаров

И больше ничего, все шаблоны для этих страниц должны быть унаследованы от базового

2024-09-20 17:27 UTC, Dimon4ik812 commented on catalog/urls.py
> +    path('product_detail/<int:product_id>', product_detail, name='product_detail')
Вот тут не понял?
надо с двух сторон закрыть ?

2024-09-20 17:35 UTC, Dimon4ik812 commented on catalog/templates/product_information.html
> +<!DOCTYPE html>
исправил

2024-09-20 18:17 UTC, painassasin commented on catalog/urls.py
> +    path('product_detail/<int:product_id>', product_detail, name='product_detail')
Нет, только в конце - у тебя все остальные эндпоинты со слешем в конце

2024-09-20 18:21 UTC, painassasin requested changes

2024-09-20 18:21 UTC, painassasin commented on catalog/templates/includes/inc_menu.html
> +        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
ссылки правильнее оформлять так:
```html
<a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Каталог</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts %}">Контакты</a>
```

2024-09-20 18:21 UTC, painassasin commented on catalog/templates/product_detail.html
> +<!doctype html>
Эта страница должна быть тоже унаследована от базового шаблона

2024-09-20 18:21 UTC, painassasin commented on catalog/views.py
> +def index(request):
Кажется этот контроллер не используется

2024-09-20 18:31 UTC, Dimon4ik812 commented on catalog/templates/includes/inc_menu.html
> +        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
исправил

2024-09-20 18:31 UTC, Dimon4ik812 commented on catalog/views.py
> +    product = Product.objects.get(id=product_id)
исправил

2024-09-20 18:32 UTC, Dimon4ik812 commented on config/settings.py
> +    'catalog'
исправил

2024-09-20 18:32 UTC, Dimon4ik812 commented on catalog/urls.py
> +    path('product_detail/<int:product_id>', product_detail, name='product_detail')
исправил

2024-09-20 18:33 UTC, Dimon4ik812 commented on catalog/views.py
> +def index(request):
исправил

2024-09-20 18:33 UTC, Dimon4ik812 commented on catalog/templates/product_detail.html
> +<!doctype html>
у меня разве не так сделано ?

2024-09-21 06:57 UTC, Dimon4ik812 commented on catalog/templates/product_detail.html
> +<!doctype html>
теперь исправил :)

2024-09-21 10:37 UTC, painassasin approved these changes

2024-09-21 10:37 UTC, painassasin commented on catalog/templates/product_detail.html
> +{% include 'includes/inc_menu.html'%}
Меню лучше не инклюдить во все шаблоны, а сделать это в home.html

2024-09-21 10:37 UTC, painassasin commented on catalog/templates/product_detail.html
> +{% include 'includes/footer.html'%}
Как и футер  - заинклюдь в home.html

2024-09-25 14:33 UTC, merged